CREATE TABLE IF NOT EXISTS users(
    user_id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    age TINYINT(3) UNSIGNED NOT NULL DEFAULT 18,
    country VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    social_media_url VARCHAR(255) NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP not null ,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP not null
);